### ISSUE TITLE
Use wallet auth to apply for program

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#154]
The user should authenticate with their wallets to apply for the affiliate program rather than entering their account name

![image](https://user-images.githubusercontent.com/5632966/128882062-3262b53d-8d9a-4421-8ffc-10103e5f001a.png)

**Comment by leisterfrancisco** [comment]
@xavier506 I think this task is already resolved, please confirm me.

**Comment by xavier506** [comment]
yes this task has been completed

**Comment by leisterfrancisco** [comment]
Thank you. Since this is already merged, I'm gonna close it.
