### ISSUE TITLE
Approve this account KYC? or is it referral payment?

### ISSUE THREAD

**Issue by RhettOP** [eoscostarica/proton-affiliate#209]
**Describe the bug**
Error message wrong. Doesn't the KYC provider do the KYC?

**Expected behavior**
Should it not be approve referral payment? Where is the background info to assess the payment?

**Screenshots**
<img width="753" alt="Screenshot 2021-08-18 at 19 51 13" src="https://user-images.githubusercontent.com/39966573/129961958-e69d2bd5-3b3b-48b7-a5c9-5a9f2276482f.png">

Desktop:
OS: MacOS Big Sur
Browser Chrome
Version Version 92.0.4515.131 (Official Build) (arm64)

**Comment by xavier506** [comment]
@RhettOP 

There are no KYC providers configured on the testnet.  We added this just for testing purposes, it is meant to simulate the step the KYC provider will complete on mainnet

This action will be removed on the mainnet instance , as KYV will depend on KYC providers.

Let me know if you have any further questions.
