### ISSUE TITLE
Dereference of end iterator

### ISSUE THREAD

**Issue by RhettOP** [eoscostarica/proton-affiliate#210]
**Describe the bug**
When approving a referral payment of affiliate13, I get this error.

<img width="364" alt="Screenshot 2021-08-18 at 20 52 38" src="https://user-images.githubusercontent.com/39966573/129963571-3518030c-3dd7-4dff-a607-10a5f0e78dbf.png">

**Comment by leisterfrancisco** [comment]
@xavier506 Is it already completed?
