### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#211]
When I sign up for an affiliate account i get prompted for my email . However i dont get notified when my account is approved

**Describe the solution you'd like**
There should be an email service that sends notifications when my user is approved

**Describe alternatives you've considered**
We can also create email notifications before my referal expires or when i get paid

**Additional context**
![image](https://user-images.githubusercontent.com/5632966/130088772-bb4040b2-3960-435f-9bd6-11f8cc464495.png)

**Comment by leisterfrancisco** [comment]
@xavier506 please, confirm this task description `There should be an email service that sends notifications when my user is approved` is already covered but is missing `We can also create email notifications before my referal expires or when i get paid`

**Comment by xavier506** [comment]
we only
wanted emails to notify users have been approved as affiliates

**Comment by leisterfrancisco** [comment]
Since the emails notification to let the users know when they are approved is already merged, I'm gonna close this task.
