### ISSUE TITLE
Show current version string

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#247]
Show the current build version on the webapp

similar to evodex 

![image](https://user-images.githubusercontent.com/5632966/131163030-f0375b03-4624-4042-b2ec-842e89476abd.png)

**Comment by murillojorge** [comment]
Let's place it next to the copyrights on the footer. Please @tetogomez  also take a look at the spacing of the elements on the footer.
Refer to: https://zpl.io/V4nEyzM

**Comment by xavier506** [comment]
![image](https://user-images.githubusercontent.com/5632966/131760171-16d44d9c-2478-45d4-a0f9-d9b6a000ea9f.png)
