### ISSUE TITLE
Enable check for mainnet instance

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#254]
The KYC check needs to be enabled for the mainnet instance

https://github.com/eoscostarica/proton-affiliate/blob/05ce76b8647a4e0ddd67de2a7bb1f3191f3cd2fe/contracts/affiliate/src/affiliate.cpp#L23

https://github.com/eoscostarica/proton-affiliate/blob/05ce76b8647a4e0ddd67de2a7bb1f3191f3cd2fe/contracts/affiliate/src/affiliate.cpp#L51

**Comment by leisterfrancisco** [comment]
Closed by https://github.com/eoscostarica/proton-affiliate/pull/255
