### ISSUE TITLE
cannot see current user on mobile

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#256]
**Describe the bug**
I cant tell what user i am logged in as on my mobile phone

**To Reproduce**
1. Go to earnproton.com on your mobile phone 
2. Click on login
3. login 
4. look for username

**Expected behavior**
I would like to see my currwnt user name for my session .

**Screenshots**
![image](https://user-images.githubusercontent.com/5632966/131426505-2f858115-4724-48c8-92df-c67c6273adb7.jpeg)

**Smartphone (please complete the following information):**
 - Device: iphone10
 - OS: iOS
 - Browser chrome

**Comment by murillojorge** [comment]
Let's include it into the user menu sheet. https://zpl.io/2EGdEle @tetogomez
