### ISSUE TITLE
Help Page Icons

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#274]
Should we add Github and Telegram icons instead of the grey boxes ?

![image](https://user-images.githubusercontent.com/5632966/132098595-fbe6c4dd-418b-44e9-bf36-9f9cdc063111.png)

![image](https://user-images.githubusercontent.com/5632966/132098485-77947bac-69e4-47fb-b3be-41f0ce9ad546.png)

**Comment by murillojorge** [comment]
Yes the actual page has the icons available. @tetogomez is aware of this.
