### ISSUE TITLE
Payment link does not display on the referral history

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#293]
The last step in the referral history is not displayed on the history.  The account MEDUSA was paid the referral fee but it did not display on the referral history. 

![Screen Shot 2021-09-16 at 1 28 02 PM](https://user-images.githubusercontent.com/40245170/133657964-10caaad1-9d7b-4baa-8ec2-a92140c4fa2c.png)

**Comment by leisterfrancisco** [comment]
It looks like happened a syncing error at that specific moment, or the worker services weren't configured when the payment occurred. Take a [look](https://www.loom.com/share/80f8b2cd483048409312bccd0912177e) when I restarted in `localhost` the syncing from Proton Mainnet using the worker service.
