### ISSUE TITLE
Latest Referral Payments is not displaying the most recent payments

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#294]
The account MEDUSA was paid a referral fee but it is not displaying in the Latest referral payment UI.  

![Screen Shot 2021-09-16 at 1 27 08 PM](https://user-images.githubusercontent.com/40245170/133658168-10485902-3760-425d-875d-c578b8772920.png)

**Comment by leisterfrancisco** [comment]
@edgarithm @xavier506  I did some tests and it looks to be working right. Transactions are not displayed in real-time, it takes [irreversibility time to be updated](https://github.com/eoscostarica/proton-affiliate/blob/dev/hapi/src/services/hyperion/index.js#L120) plus the time all [updaters take](https://github.com/eoscostarica/proton-affiliate/blob/dev/hapi/src/services/hyperion/index.js#L94-L107) to complete their actions.

Have in mind that the irreversibility time used in this algorithm is [164 seconds](https://github.com/eoscostarica/proton-affiliate/blob/dev/hapi/src/services/hyperion/index.js#L10).
