### ISSUE TITLE
Referral payment amount is not displayed in the Admin Referral Payment section

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#295]
The amount paid to the referral is not displayed as it should be in the admin table.   The account MEDUSA appears as PAID but the referral amount is not displayed.  
![Screen Shot 2021-09-16 at 1 32 17 PM](https://user-images.githubusercontent.com/40245170/133658473-e1cc54b5-e13c-44f4-a9d7-5e436614185b.png)

**Comment by leisterfrancisco** [comment]
@edgarithm MEDUSA account has a different scenario, unlike other accounts. When MEDUSA gets paid, seems like the backend worker services haven't been deployed and for that reason didn't register that transaction in our database.
