### ISSUE TITLE
Wallet authentication to apply as an affiliate 

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#305]
**Is your feature request related to a problem? Please describe.**
There is currently no need to authenticate with wallet to apply as an affiliate

**Describe the solution you'd like**
It would be better if users need to authenticate with their wallets to apply as an affiliate

**Comment by leisterfrancisco** [comment]
@xavier506 @murillojorge does it requires more steps to apply as an affiliate, doesn't it?

**Comment by murillojorge** [comment]
Clicking on the Join button would bring up the Wallet. Then the account input will be filled with the actual account and not editable. The user fills email and send the request.
