### ISSUE TITLE
Admin need to know which affiliates are eligible

### ISSUE THREAD

**Issue by murillojorge** [eoscostarica/proton-affiliate#310]
"As an admin I need to know which affiliate requests are eligible so I can batch approve them easily."

The main requirement is KYC, so let's add a column (Eligibility) into the admin table showing if the user is "Eligible" or "Missing KYC"

**Comment by leisterfrancisco** [comment]
closed because of [this card](https://github.com/eoscostarica/proton-affiliate/issues/320)
