### ISSUE TITLE
Frontend KYC validation for affiliate application

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#320]
Users can apply as an affiliate only if they have completed KYC.

**Comment by xavier506** [comment]
you can also apply to be an affiliate even if you already are an affiliate 

![image](https://user-images.githubusercontent.com/5632966/139589006-bd01bf4d-19d7-42f9-b161-0edbad334c63.png)


we need to include an additional validation to only allow accounts that are not currently affiliates to apply.

**Comment by leisterfrancisco** [comment]
@xavier506 if we do it in this way, then [this is not](https://github.com/eoscostarica/proton-affiliate/issues/310) going to be needed, I mean, that scenario described on the card never gonna happen, is it?
