### ISSUE TITLE
[Security] Workflow push-prod-environment.yaml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by Ale0x78** [eoscostarica/proton-affiliate#339]
The workflow push-prod-environment.yaml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by leisterfrancisco** [comment]
Take a look at the official documentation for [Checkout V2](https://github.com/marketplace/actions/checkout)

**Comment by leisterfrancisco** [comment]
Already solved in https://github.com/eoscostarica/proton-affiliate/pull/369
