### ISSUE TITLE
Unknown Requester using WebAuth Wallet

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#342]
EarnProton.com should be a known requestor on the WebAuth wallet. 
![image](https://user-images.githubusercontent.com/40245170/147965249-2390756b-e361-4457-8969-baa24544908e.png)

**Comment by leisterfrancisco** [comment]
@xavier506 more and less what should I investigate to make earnproton a know requestor for WebAuth Wallet?

**Comment by xavier506** [comment]
I think we need to contact the wallet developers

**Comment by leisterfrancisco** [comment]
@edgarithm could you provide me information about what did you do to get that warning message. I ask this because WebAuth.com is not implemented yet in proton-affiliate project.

**Comment by leisterfrancisco** [comment]
I also tried with Proton Wallet App but didn't get the error.

**Comment by leisterfrancisco** [comment]
@xavier506 I just noticed the error happen when we try to authenticate using `Proton Wallet` to start using Proton Affiliate Program but validating with the `WebAuth.com` app, wouldn't be needed to integrate this new authentication method?
