### ISSUE TITLE
Wallet Links on Apple Store and Play Store should link to new WebAuth wallet

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#343]
These buttons should link to new WebAuth wallet download links. 

Links here: https://webauth.com/login

After joining as a referral, there is a modal with a link to download a wallet. It is needed to update this link to webauth wallet

![image](https://user-images.githubusercontent.com/40245170/147965390-726bb7b7-bfa7-4c54-8fee-51f2ac7aa7df.png)

**Comment by leisterfrancisco** [comment]
@edgarithm are you sure the link should go there? Wouldn't be better to link to their respective OS Store, like:

App Store: https://apps.apple.com/us/app/webauth-com/id1594500069
Google Play: https://play.google.com/store/apps/details?id=com.metallicus.webauth
