### ISSUE TITLE
User should be able to Filter by Status in the User Management Table in the Admin Section

### ISSUE THREAD

**Issue by edgarithm** [eoscostarica/proton-affiliate#344]
Add a filter to this section to filter between status types "admin" or "referrer" 

![image](https://user-images.githubusercontent.com/40245170/147965612-5667344e-a609-428d-a621-9f780b64943a.png)

**Comment by leisterfrancisco** [comment]
@edgarithm is it by status or by role?

**Comment by murillojorge** [comment]
This initial version of the filter button is a one selection only component. If admins require more filtering we can create a multiple selection comp later on. @leisterfrancisco 
https://zpl.io/aBnREzQ

![Admin Filtering](https://user-images.githubusercontent.com/1179619/148312562-be89b4e4-5422-486e-aaec-8c5d08f4e566.png)
