### ISSUE TITLE
Latest payments not updating

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/proton-affiliate#359]
There have been payments completed since the last ones shown on the homepage. It appears the list is not updating 

![image](https://user-images.githubusercontent.com/5632966/149667510-90a4db80-b744-47b2-ac2d-f213fa7c06f3.png)

**Comment by xavier506** [comment]
perhaps we should consider showing all the different referal status here (not just paid)

![image](https://user-images.githubusercontent.com/5632966/149667836-9f2c9d03-dc37-4eed-b71b-1c06705850b9.png)

**Comment by leisterfrancisco** [comment]
The idea is to add that table to the homepage? Or add to the Latest Referral Payments table the Referral Payments columns?

**Comment by leisterfrancisco** [comment]
This task seems to be duplicated to #294, however, this card describes a nice cool feature that could be added to the Proton Affiliate program. This new feature is described in #375
